lab1: lab1.cpp
	g++ -O0 lab1.cpp -o lab1

lab2: lab2.cpp
	g++ -O0 lab2.cpp -o lab2

lab3: lab3.cpp
	g++ -O0 lab3.cpp -o lab3

lab4: lab4.cpp
	g++ -O0 lab4.cpp -o lab4

clean:
	rm -f lab1
	rm -f lab2
	rm -f lab3
	rm -f benchmark